spring:
  application:
    name: appointments-flyway
  datasource:
    url: jdbc:postgresql://localhost:5432/appointmentsdb
    username: flywaylocal
    password: pass
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
